### ISSUE TITLE
multiple imports on one line are no longer valid as of p1703

### ISSUE THREAD

**Issue by RedBeard0531** [mathstuf/cxx-modules-sandbox#18]
https://github.com/mathstuf/cxx-modules-sandbox/blob/8ee53de2199df8a01e21fb45b62ed9164b5333e0/good-scanner/multi-line.mpp#L1

This is bullet 3 of the p1703 proposal that was extended to cover named modules as well as header units.

This was the main test my implementation was failing, and now I'm happy I don't have to fix it 😄

**Comment by mathstuf** [comment]
This file doesn't exist anymore (3183d38601bc9daffbce187e855fb8eed1cd3b7a)
