### ISSUE TITLE
Error: ‘import’ does not name a type; did you mean ‘short’?

### ISSUE THREAD

**Issue by Lotte1990** [mathstuf/cxx-modules-sandbox#23]
I'm getting the following error:

`error: ‘import’ does not name a type; did you mean ‘short’?`

What am I doing wrong?

Ubuntu 18.04
CMake 3.17.0
GCC 7.5.0

**Comment by Warchant** [comment]
You're using wrong compiler. https://en.cppreference.com/w/cpp/compiler_support Modules feature is not even in gcc10

**Comment by johan-boule** [comment]
Please try with the docker branch of this repository: it contains compilers with module support.
