### ISSUE TITLE
Update code to be more uniform

### ISSUE THREAD

**Issue by mathstuf** [mathstuf/cxx-modules-sandbox#5]
Primarily:

  - `.mpp` extensions for module interface files (with an example not using this extension)
  - match module names with file basenames (with an example using mismatching names)

See discussion in #3.

**Comment by johan-boule** [comment]
Also, having both `foo.mpp` and `foo.cpp` in the same directory is interesting to test the build systems are not trying to produce `foo.o` for both.

**Comment by mathstuf** [comment]
Good idea. Added to #7.

**Comment by mathstuf** [comment]
One problem I'm seeing right now is that GCC doesn't recognize `.mpp` extensions as C++ source requiring an `-x c++` flag to be passed.

**Comment by mathstuf** [comment]
Cc: @urnathan

**Comment by mathstuf** [comment]
@johan-boule If you want to update the Dockerfile and the code, CMake commit cf0da507ad34c1748ef6125e8c4a7923a0d8b144 can build `.mpp` sources. However, I'd like to know what it would take to get a GCC and Clang to understand the extension natively.
